[22-10-29 00:08:22,728]main.py:(17)-DEBUG - 1666982302.728725
[22-10-29 00:08:22,728]main.py:(19)-INFO - Log aggregation started
[22-10-29 00:08:22,729]main.py:(20)-INFO - ******************************
[22-10-29 00:08:22,729]main.py:(23)-DEBUG - Number of arguments passed is 3
[22-10-29 00:08:22,729]main.py:(26)-DEBUG - Arguments passed are : 9845000012 and 20210923
[22-10-29 00:08:22,729]/UMAR/python/automation/log_aggregator/input_validation.py:(24)-DEBUG - msisdn entered is valid : 9845000012
[22-10-29 00:08:22,734]/UMAR/python/automation/log_aggregator/input_validation.py:(39)-DEBUG - Transaction date entered is valid : 20210923
[22-10-29 00:08:22,940]main.py:(41)-WARNING - Tomcat path not initialized. tomcat process is not running
[22-10-29 00:08:23,130]main.py:(47)-DEBUG - Prism path initialized
[22-10-29 00:08:23,130]/UMAR/python/automation/log_aggregator/log_processor.py:(24)-DEBUG - Prism tlog path exists.
[22-10-29 00:08:23,349]/UMAR/python/automation/log_aggregator/log_files.py:(26)-DEBUG - Prism BILLING tlog path exists.
[22-10-29 00:08:23,548]/UMAR/python/automation/log_aggregator/log_files.py:(52)-ERROR - Prism billing tlog directory does not have 20210923 dated files
[22-10-29 00:08:23,548]/UMAR/python/automation/log_aggregator/tlog_parser.py:(44)-DEBUG - No tlog found for given msisdn: 9845000012
[22-10-29 00:08:23,549]/UMAR/python/automation/log_aggregator/log_processor.py:(30)-DEBUG - No issue tlog found for prism. Hence not fetching the prism log.
[22-10-29 00:08:23,549]main.py:(64)-INFO - Log aggregation finished
[22-10-29 00:08:23,549]main.py:(65)-INFO - **********************************
[22-10-29 00:08:23,549]main.py:(77)-DEBUG - 1666982303.5494444
[22-10-29 00:08:23,549]main.py:(80)-DEBUG - Total time taken 0.8207194805145264
