[22-10-31 14:12:40,541]main.py:(17)-DEBUG - 1667205760.5412464
[22-10-31 14:12:40,541]main.py:(19)-INFO - Log aggregation started
[22-10-31 14:12:40,541]main.py:(20)-INFO - ******************************
[22-10-31 14:12:40,541]main.py:(23)-DEBUG - Number of arguments passed is 3
[22-10-31 14:12:40,541]main.py:(26)-DEBUG - Arguments passed are : 9845000012 and 20220923
[22-10-31 14:12:40,541]/UMAR/python/automation/log_aggregator/input_validation.py:(24)-DEBUG - msisdn entered is valid : 9845000012
[22-10-31 14:12:40,547]/UMAR/python/automation/log_aggregator/input_validation.py:(38)-DEBUG - Transaction date entered is valid : 20220923
[22-10-31 14:12:40,776]main.py:(39)-DEBUG - Tomcat path initialized
[22-10-31 14:12:40,972]main.py:(47)-DEBUG - Prism path initialized
[22-10-31 14:12:40,972]/UMAR/python/automation/log_aggregator/log_processor.py:(22)-DEBUG - Tomcat tlog path exists.
[22-10-31 14:12:40,973]/UMAR/python/automation/log_aggregator/log_files.py:(44)-DEBUG - Tomcat BILLING tlog path exists.
[22-10-31 14:12:40,973]/UMAR/python/automation/log_aggregator/log_files.py:(89)-INFO - tomcat tlog path: /PRISM/TOMCAT/apache-tomcat-8.0.48/TOMCAT_LOGS/TLOG/BILLING_REALTIME
[22-10-31 14:12:40,976]/UMAR/python/automation/log_aggregator/log_files.py:(99)-ERROR - Tomcat billing tlog directory does not have 20220923 dated files
[22-10-31 14:12:40,976]/UMAR/python/automation/log_aggregator/tlog_parser.py:(78)-ERROR - No tomcat tlog found for given msisdn: 9845000012
[22-10-31 14:12:40,976]/UMAR/python/automation/log_aggregator/log_processor.py:(28)-ERROR - No issue tlog found. Hence not fetching the tomcat log.
[22-10-31 14:12:40,977]/UMAR/python/automation/log_aggregator/log_processor.py:(31)-DEBUG - Prism tlog path exists.
[22-10-31 14:12:40,977]/UMAR/python/automation/log_aggregator/log_files.py:(31)-DEBUG - Prism BILLING tlog path exists.
[22-10-31 14:12:40,983]/UMAR/python/automation/log_aggregator/log_processor.py:(33)-DEBUG - Prism tlog parsed successfully
[22-10-31 14:12:40,983]/UMAR/python/automation/log_aggregator/log_parser.py:(31)-DEBUG - Parsing daemon log
[22-10-31 14:12:40,990]/UMAR/python/automation/log_aggregator/log_parser.py:(45)-DEBUG - Getting daemon log for the issue thread : WORKER_76_178971
[22-10-31 14:12:41,29]/UMAR/python/automation/log_aggregator/daemon_log.py:(78)-WARNING - Prism daemon log path does not exists or issue thread [WORKER_76_178971] could not be found.
[22-10-31 14:12:41,30]/UMAR/python/automation/log_aggregator/daemon_log.py:(79)-DEBUG - Going to check root log.
[22-10-31 14:12:41,32]/UMAR/python/automation/log_aggregator/daemon_log.py:(87)-WARNING - Prism root log path does not exists or issue thread [WORKER_76_178971] could not be found.
[22-10-31 14:12:41,32]/UMAR/python/automation/log_aggregator/daemon_log.py:(88)-DEBUG - Going to check prism backup log path
[22-10-31 14:12:44,508]/UMAR/python/automation/log_aggregator/daemon_log.py:(93)-DEBUG - Issue thread [WORKER_76_178971] found in prism daemon backup log and will be parsed for any issue.
[22-10-31 14:12:44,782]main.py:(64)-INFO - Log aggregation finished
[22-10-31 14:12:44,782]main.py:(65)-INFO - **********************************
[22-10-31 14:12:44,782]main.py:(77)-DEBUG - 1667205764.7826748
[22-10-31 14:12:44,782]main.py:(80)-DEBUG - Total time taken 4.241428375244141
